// Application Constants & Configuration
export const VEHICLES = ['LL6850', 'HU5155', 'NE5155']; 
export const Number_prefix = "MH14";

export const CONFIG = {
  fileName: 'logistics_log.xlsx',
  maxLengths: {
    challanNo: 20,
    gateNo: 8
  },
  loadingLocations: [
    "A.C.P.L.",
    "A.M.",
    "A.P.Q.",
    "AAISAHEB",
    "ADITYA",
    "AM",
    "APQ",
    "B17",
    "BAJAJ AK01",
    "BAJAJ CH01",
    "BAJAJ CK01",
    "BELRICE",
    "BELRISE",
    "C,14",
    "C,15",
    "C14",
    "C15",
    "CK01",
    "ENDURANCE",
    "ICQR",
    "J.K.",
    "JEENA",
    "JEENA, CR61",
    "JK",
    "JYOTI",
    "KAWASAKI",
    "LUMAX",
    "LUMAX CR62",
    "MAHALAXMI",
    "METPROTE",
    "METPROTECT",
    "MHA, LAXI",
    "MINDA, CH78",
    "OCTILLON",
    "PARSHWANATH",
    "PASHWANATH",
    "PUNE MEETAL",
    "PURFLUX",
    "PURLUX",
    "S.M. AUTO, CRS3",
    "SEABIRD",
    "SHIVINAYAK",
    "SHREE LAXMI",
    "SHRILAXMI",
    "SHRIVINAYAK",
    "STARWAYS",
    "TATA",
    "TRIPLEX",
    "UNIVERSAL",
    "UNO MINDA",
    "VARROC",
    "VIJAY",
    "WELLOAT"
  ],
  unloadingLocations: [
    "A.C.P.L.",
    "A.M.",
    "A.P.Q.",
    "AAISAHEB",
    "ADITYA",
    "AM",
    "APQ",
    "B17",
    "BAJAJ AK01",
    "BAJAJ CH01",
    "BAJAJ CK01",
    "BELRICE",
    "BELRISE",
    "C,14",
    "C,15",
    "C14",
    "C15",
    "CK01",
    "ENDURANCE",
    "ICQR",
    "J.K.",
    "JEENA",
    "JEENA, CR61",
    "JK",
    "JYOTI",
    "KAWASAKI",
    "LUMAX",
    "LUMAX CR62",
    "MAHALAXMI",
    "METPROTE",
    "METPROTECT",
    "MHA, LAXI",
    "MINDA, CH78",
    "OCTILLON",
    "PARSHWANATH",
    "PASHWANATH",
    "PUNE MEETAL",
    "PURFLUX",
    "PURLUX",
    "S.M. AUTO, CRS3",
    "SEABIRD",
    "SHIVINAYAK",
    "SHREE LAXMI",
    "SHRILAXMI",
    "SHRIVINAYAK",
    "STARWAYS",
    "TATA",
    "TRIPLEX",
    "UNIVERSAL",
    "UNO MINDA",
    "VARROC",
    "VIJAY",
    "WELLOAT"
  ]
};
